apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-configmap
  namespace: metallb-system
data:
  config: | 
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.10-192.168.1.15