- hosts: Sonarqube_node
  become: true
  tasks:
    - name: Create Docker Group
      become: yes
      command: sudo groupadd docker > /dev/null

    - name: Add Current User to Docker Group
      become: yes
      command: sudo usermod -aG docker $USER > /dev/null

    